server:
  port: 80

spring:
  devtools:
    add-properties: false
    livereload:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false
  data:
    redis:
      host: localhost
      port: 6379
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: error
        type.descriptor.sql: error