server:
  port: 80

spring:
  devtools:
    add-properties: false
    livereload:
      enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: https://api.jwt.abz.kr/login/oauth2/code/google
          naver:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: https://api.jwt.abz.kr/login/oauth2/code/naver
          kakao:
            client-id: client-id
            client-secret: client-secret
            redirect-uri: https://api.jwt.abz.kr/login/oauth2/code/kakao
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false
  data:
    redis:
      host: localhost
      port: 6379
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace

recaptcha:
  secret: secret
aws:
  ses:
    access_key: access_key
    secret_key: secret_key
jwt:
  access_secret: access_secret
  refresh_secret: refresh_secret
frontend:
  url: https://jwt.abz.kr